name: Client Unit Tests

on:
  - push
  - pull_request

jobs:
  python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install setuptools
        make install-dev
        echo "::add-path::$HOME/.local/bin"
    - name: Check format
      run: |
        make check-format
    - name: Test
      run: |
        make test
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./.coverage
        flags: unittests
        env_vars: OS,PYTHON
        name: ci-codecov
        fail_ci_if_error: true
